# Generated by Django 5.1.2 on 2024-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/movie_banners/'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='media/screenshots/'),
        ),
    ]
