# Generated by Django 5.1.2 on 2024-11-03 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_movie_banner_image_alter_screenshot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_movies', to='moviesapp.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
