# Generated by Django 5.1.2 on 2024-11-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_upcomingmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
