# Generated by Django 5.1.2 on 2024-11-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0004_movie_banner_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='banner_image',
        ),
    ]
