# Generated by Django 5.1.2 on 2024-11-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_remove_movie_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner_image_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
