# Generated by Django 5.1.2 on 2024-11-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0006_alter_movie_banner_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='summary',
            field=models.TextField(default='Harry Potter, an eleven-year-old orphan, discovers that he is a wizard and is invited to study at Hogwarts. Even as he escapes a dreary life and enters a world of magic, he finds trouble awaiting him.'),
            preserve_default=False,
        ),
    ]
