# Generated by Django 5.1.2 on 2024-11-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0007_movieinfo_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
